### ISSUE TITLE
Friday doesn't work

### ISSUE THREAD

**Issue by jrlester70** [AnykeyNL/OCI-AutoScale#13]
If I have a tag: *,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*
Then this works if I select AnyDay, but If I select Friday only it says I've not entered enough values:

Checking instance-20210817-0927 (Instance)...
 - Active schedule for instance-20210817-0927: *,*,*,*,*,*,*,[*],*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,
 - Ignoring this service for this hour
Checking cgretailsapps (Instance)...
 - Error with schedule of cgretailsapps - , not correct amount of hours, i count 1

(these 2 instances have the same tag, one works, one doesn't)

**Comment by AnykeyNL** [comment]
Issue has been fixed. you got this error when there was an single day schedule, but not one on the day the script was being run.

**Comment by jrlester70** [comment]
Perfect, thanks ! I typically hadn’t tried it for today, but that’s a much nicer error now as well.
