### ISSUE TITLE
I'm getting this error, could you guys help me?

### ISSUE THREAD

**Issue by yvssva** [AnykeyNL/OCI-AutoScale#17]
[opc@autoscaler OCI-AutoScale]$ python3 CreateNameSpaces.py
Traceback (most recent call last):
  File "CreateNameSpaces.py", line 33, in <module>
    config, signer = OCIFunctions.create_signer(cmd.config_profile, cmd.is_instance_principals, cmd.is_delegation_token)
  File "/home/opc/OCI-AutoScale/OCIFunctions.py", line 60, in create_signer
    (config_profile if config_profile else oci.config.DEFAULT_PROFILE)
  File "/usr/lib/python3.6/site-packages/oci/config.py", line 106, in from_file
    raise ConfigFileNotFound("Could not find config file at {}, please follow the instructions in the link to setup the config file https://docs.cloud.oracle.com/en-us/iaas/Content/API/Concepts/sdkconfig.htm".format(expanded_file_location))
oci.exceptions.ConfigFileNotFound: Could not find config file at /home/opc/.oci/config, please follow the instructions in the link to setup the config file https://docs.cloud.oracle.com/en-us/iaas/Content/API/Concepts/sdkconfig.htm
[opc@autoscaler OCI-AutoScale]$

**Comment by AnykeyNL** [comment]
looks like you did not configure the OCI authentication.

Please run the command: oci setup config
then provided the asked details. When the keys are generated. Upload the public key to your user profile in OCI under the API keys section.

**Comment by yvssva** [comment]
All right! We missed that part, in the autoscaler VM, has to configure the oci-cli properly.

Thank you!
