### ISSUE TITLE
Crontab

### ISSUE THREAD

**Issue by yvssva** [AnykeyNL/OCI-AutoScale#18]
Hi, i'm not sure if the script was added in crontab, because de automation is not working, how i can check this?

**Comment by AnykeyNL** [comment]
You can test the script by just running it manually and see what output it gives you.

**Comment by yvssva** [comment]
Hi Richard, thanks for your reply.

The scripts are fine, but, the automation is not working.

We are testing a Anyday TAG in a VM (compute instance), and the powerup trigger works (0,0,0,0,1,1,1,1,1,0,0...) but the 0,0,0,0 doenst shutdown the VM, we had a suspicious was a crontab problems but its not.

The scripts works just fine when is manually executed, but the automation by himself doenst look allright.

How i could investigate better, is there some logs?
