### ISSUE TITLE
Script does not work for Exadata VM cluster

### ISSUE THREAD

**Issue by kyaqoub** [AnykeyNL/OCI-AutoScale#19]
the script runs fine against VMs but when I add the schedule to a VM cluster, it simply does nothing!
Some how it does not recognize the schedule! I even deleted the schedule and then added the tag but didn't help. Here is the output when I run the script manually:
Loading Compartments...
    Total 4 compartments loaded.

##########################################################################################
#                                  Region us-ashburn-1                                   #
##########################################################################################
Starting Auto Scaling script on region us-ashburn-1, executing All actions
Debug: 2022-04-23 07:03:14.950558
Day of week: Saturday, IsWeekday: False,  Current hour: 7,  Current DayOfMonth: 23
Getting all resources supported by the search function...
Finding MySQL instances in 4 Compartments...
....

Checking 2 Resources for Auto Scale...
Checking s2ts-12c-05 (Instance)...
 - Active schedule for s2ts-12c-05: 0,0,0,0,0,0,0,[0],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
Checking EXACSX8 (CloudVmCluster)...
Waiting for all threads to complete...
Region us-ashburn-1 Completed.

##########################################################################################
#                                  Region us-phoenix-1                                   #
##########################################################################################
Starting Auto Scaling script on region us-phoenix-1, executing All actions
Debug: 2022-04-23 04:03:14.950558
Day of week: Saturday, IsWeekday: False,  Current hour: 4,  Current DayOfMonth: 23
Getting all resources supported by the search function...
Finding MySQL instances in 4 Compartments...
....

Checking 1 Resources for Auto Scale...
Checking s2ts-12c-dev (Instance)...
 - Active schedule for s2ts-12c-dev: 0,0,0,0,[0],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
Waiting for all threads to complete...
Region us-phoenix-1 Completed.
All scaling tasks done, checked 3 resources.

**Comment by AnykeyNL** [comment]
Is fixed now
