### ISSUE TITLE
AutoScale VM Instance not working

### ISSUE THREAD

**Issue by RosasAustral** [AnykeyNL/OCI-AutoScale#21]
The autoscaleall.py doesn’t have the auto scale for VM Instances commands… please include it, abs add the flex shape option.
Thanks

**Comment by flynnkc** [comment]
+1

**Comment by therealcmj** [comment]
@RosasAustral Pull 22 **may** fix your issue. Give that a shot

**Comment by AnykeyNL** [comment]
I have added support for changing the CPU and Memory count for Compute Flex shapes. Just understand that this will reboot the instance!
