### ISSUE TITLE
Setup for specific compartment (not tenancy)

### ISSUE THREAD

**Issue by caleb-melchizedek** [AnykeyNL/OCI-AutoScale#25]
Thanks for the help on this we are set up the policy at compartment level to manage resources in a specific compartment.
How do we adjust the python scripts to suite this, since the auto scale python scripts were written for tenancy management?

Thank you.
l

**Comment by AnykeyNL** [comment]
You should be able to use the  -ic  (- include compartment ocid) parameter to just specify the compartment you want the script to check.

**Comment by caleb-melchizedek** [comment]
Alright I have seen the commented command line parameters. in the AutoScaleAll.py file.
But just to clarify, do I add the parameter to the " bash install.sh" command?

**Comment by AnykeyNL** [comment]
Just run normal install and the edit crontab (crontab -e) and just add it there.

**Comment by caleb-melchizedek** [comment]
Hi, I want to find out, must the instance be use autonomous linux image eg. Autonomous Linux 7.9 image?
or it can be any other type on linux image?

**Comment by AnykeyNL** [comment]
Instance can be anything that can run pyhton and the OCI SDK. So any linux/windows even the ARM vms can be used.

**Comment by caleb-melchizedek** [comment]
ALright thank you.
