### ISSUE TITLE
Incorrect region and API spec

### ISSUE THREAD

**Issue by jrlester70** [AnykeyNL/OCI-AutoScale#26]
Running this with uk-gov-london-1 as our home region:

[xxx@xxxOCI-AutoScale]$ python3 CreateNameSpaces.py -ip
Starts at 2023-02-23 18:52:27

Connecting to Identity Service...

Tenant Name   : xxxx
Tenant Id     : ocid1.tenancy.oc4..xxx
Home Region   : uk-gov-london-1

but the server we're running on is in the second region, newport. My config file only specifies london at the moment.

The script errors trying to create the namespace the the standard 403 error, and when I can see the traceback it's trying to call :

'request_endpoint': 'POST https://identity.uk-gov-cardiff-1.oci.oraclegovcloud.uk/20160918/tagNamespaces'

so somehow it's got the secondary site (which wont work).. I don't see why it's not using the URL for our primary site, but this means I can't create the namespaces.

J

**Comment by AnykeyNL** [comment]
you can just create the namespaces manually if you like. Just create a namespace "Schedule" and in they name space the predefined tags.that the autoscale script is ready to be usedOn 23 Feb 2023, at 19:56, jrlester70 ***@***.***> wrote:﻿
Running this with uk-gov-london-1 as our home region:
***@***.***$ python3 CreateNameSpaces.py -ip
Starts at 2023-02-23 18:52:27
Connecting to Identity Service...
Tenant Name   : xxxx
Tenant Id     : ocid1.tenancy.oc4..xxx
Home Region   : uk-gov-london-1
but the server we're running on is in the second region, newport. My config file only specifies london at the moment.
The script errors trying to create the namespace the the standard 403 error, and when I can see the traceback it's trying to call :
'request_endpoint': 'POST https://identity.uk-gov-cardiff-1.oci.oraclegovcloud.uk/20160918/tagNamespaces'
so somehow it's got the secondary site (which wont work).. I don't see why it's not using the URL for our primary site, but this means I can't create the namespaces.
J

**Comment by jrlester70** [comment]
Hey Richard,

 

No, I absolutely did that, I just wanted to highlight that the auto generation script didn’t work for some reason, and thought you might like to know. It’s working fine in our environment now I’ve created the namespace, so it was just that creation script. Looks like you need to run the creation script in the home region only, and for some reason it seems to be processing our second region first.. this doesn’t cause a problem for the stop/start stuff, but obviously does for the namespace..

 

Jason

**Comment by AnykeyNL** [comment]
Thanks for the feedback. When I have some time I will look in to approving that namespace script, it can for sure use some improvements :-)
