### ISSUE TITLE
A bit of confusion from the documentation.

### ISSUE THREAD

**Issue by gwingnhbc** [AnykeyNL/OCI-AutoScale#27]
Thanks for sharing this really useful utility.  It is working great now for  our first use of controlling VMs but there were some anomalies in README.md which initially made me think we had a fault.

a) README :NEW:  states "changing the CPU and Memory Count for Compute Flex Shapes (WILL REBOOT THE INSTANCE!!)" 
For me it changes the shape but  also stops the VM and leaves it in that state.  If this is the expected  behavior it makes the recommendation to run scaling up actions just after the hour questionable as scaling up a VM  just after the hour would leave it powered down for an hour before it  actually starts (not what you want if you are sizing up a VM because the system is busy).

b) README:HowToUse:Values for the AnyDay, Weekday, Weekend and Day of week tags:   states "The value of the tag needs to contain 24 numbers and/or wildcards (*) (else it is ignored), separated by commas. If the value is 0 it will power off the resource (if that is supported for that resource). Any number higher then 0 will re-scale the resource to that number."
For me values 0 and * work as described. Value 1 starts the VM but does not re-scale it. Values 2 or higher are ignored silently rather than either re-scaling or starting the VM.

Thanks again :-)

**Comment by rajeshvarun** [comment]
Same in my case, when value is set to 2 or higher the instance status is unchanged..
+
I understand that autoscaling doesn't work for DB Instance as well..

**Comment by AnykeyNL** [comment]
Fixed the documentation. Resizing flex shapes require the (core:memory) notation. Other service like Database just require a single core number to resize.
