### ISSUE TITLE
Autonomous Linux no longer supported on Free Tier - VM.Standard.A1.Flex

### ISSUE THREAD

**Issue by marcocanto** [AnykeyNL/OCI-AutoScale#31]
Can not select any Autonomous Linux Instances when using the Free Tier Compute Resources. 

No longer supported according to this [documentation](https://www.oracle.com/a/ocom/docs/oracle-linux-for-cloud-infrastructure-faq.pdf).

Also can be seen here in the console.
![image](https://github.com/AnykeyNL/OCI-AutoScale/assets/37146863/3e2e7719-c27a-43b8-9fd9-165529a5a7c1)

**Comment by AnykeyNL** [comment]
fixed docs to Oracle Linux
