### ISSUE TITLE
When script installed on Oracle Base Database, it doesn't work

### ISSUE THREAD

**Issue by arjen-keesy** [AnykeyNL/OCI-AutoScale#33]
I have installed it on an Oracle Base Database environment, but when executing the script, the OCI library doesn't connect to my own  tenant, but to some oracle internal tenant ( dbaascpfra1 ), and of course that will not work, because it can not find any of my Services.
Any idea how to let the script connect to the right tenant ?

**Comment by AnykeyNL** [comment]
Oracle Database Service does not run in your own tenancy, but is managed by oracle / running in Oracle's tenancy. So you can not use Instance Principle to have the right permissions. If you do want to run the script inside that instance, you need to configure the OCI CLI for normal config authentication. You can run the **_oci setup config_** command to configure this. Also make sure the API key is then added to your user's profile.
