### ISSUE TITLE
Instance Shutdown not correlating with Tag Value 

### ISSUE THREAD

**Issue by Bclavelmythics** [AnykeyNL/OCI-AutoScale#36]
Currently I have the tag value set to have the instance start up at 8am est or 13 UTC and shutdown at 8pm or 1 UTC. In the screenshot you can see that the instance has a 0 for 8pm but it did not shutdown till 9pm or 2  UTC. The instance started up properly at 8am (can't see it in the screenshot because the instance was created ~9am). I tested having the value set so that the instance starts up at 7am and shuts down at 7pm and once again, it started up properly at 7am but shut down an hour late at 8pm. Wondering if there may be a flaw with the script. 

![SCR-20240102-sihc](https://github.com/AnykeyNL/OCI-AutoScale/assets/155582721/2d7293b2-8c22-4d22-81aa-caaac5d18e5d)
![SCR-20240102-sipb](https://github.com/AnykeyNL/OCI-AutoScale/assets/155582721/d920b92e-71e5-4202-8967-154b14585472)

**Comment by Bclavelmythics** [comment]
> Is the screenshot taken at the 8pm run of the script? Because in the this screenshot the bracket show the identified current hour and it says 0 and its state is also as Stopped.

The screenshot was taken during the 9pm hour so there was a 0 before that which should have stopped the instance at 8pm but did not.

**Comment by RichardORCL** [comment]
Agree, did you screenshot that or have a log. I want to see that the detected state of the instance was as that moment

**Comment by Bclavelmythics** [comment]
> Agree, did you screenshot that or have a log. I want to see that the detected state of the instance was as that momemt

So the logs of the target instance show it still being up until what is shown in the screenshot which is 9pm. Although what is interesting is previously I had noticed the instance was still up well into 8pm so I ran the script and when I did it recognized the zero and shutdown immediately. However even after that happened it went back to shutting down an hour late at 9pm.

**Comment by RichardORCL** [comment]
It should not run a "shutting down" if the VM already has a stopped state. In the screenshot of 9pm, I also do not see it take an actual action to that VM.

**Comment by RichardORCL** [comment]
Are you recording the logs or sending the logs to the OCI Message Service? This could help troubleshoot the issue next time

**Comment by Bclavelmythics** [comment]
I can't recall whether it ran a a shutdown or stopping but for the logs, however for the logs I checked the /var/log/messages to see when the instance had started up and shutdown which aligned with what showed in the metrics.

**Comment by RichardORCL** [comment]
Yes, but I need to see the log of the script output to identify if/what is wrong and what I can do to fix it :-)

**Comment by Bclavelmythics** [comment]
Ok I will get this set up and get back to you.

**Comment by Bclavelmythics** [comment]
Just wanted to confirm what you meant by the log of the script output.  `python3 AutoScaleAll.py -ip > test.txt`. Let me know if you meant otherwise.

**Comment by Bclavelmythics** [comment]
> Yes, but I need to see the log of the script output to identify if/what is wrong and what I can do to fix it :-)

Here is what I believe you mean by the script output. This wasn't till 9pm so if you need the output during the 8pm hour I can provide that to you later on this evening.
[logfile.txt](https://github.com/AnykeyNL/OCI-AutoScale/files/13831223/logfile.txt)

**Comment by RichardORCL** [comment]
Yes, please. the current output shows current hour is 21, and the VM state is already stopped, hence it is not taking any actions

**Comment by Bclavelmythics** [comment]
> Yes, please. the current output shows current hour is 21, and the VM state is already stopped, hence it is not taking any actions

Ok I will capture the output later on this evening and get back to. Thank you for the assistance.

**Comment by Bclavelmythics** [comment]
Attached is the output of the script being ran at 8:15. So the script recognizes the 0, hence the bracket, but doesn't stop it. I will note two things

1. After getting the output of the script, the instance has stopped because of it.
2. Generating a new output of the script with the instance stopped as a result from above, the script still shows it being in a running state.

[logfiletest.txt](https://github.com/AnykeyNL/OCI-AutoScale/files/13836896/logfiletest.txt)

**Comment by Bclavelmythics** [comment]
> Yes, please. the current output shows current hour is 21, and the VM state is already stopped, hence it is not taking any actions

Just wanted to quote reply just in case you weren't notified of the above message.

**Comment by RichardORCL** [comment]
The log show that it is shutting down the VM:  - Initiate Compute VM shutdown for ASTEST

Are you saying this is not actually happening?

**Comment by Bclavelmythics** [comment]
> The log show that it is shutting down the VM: - Initiate Compute VM shutdown for ASTEST
> 
> Are you saying this is not actually happening?

Correct, only when I generate the log of the script does it actually enter the shutdown process. Since I have it set to stop at 8pm, it should stop around 8pm, not after I run the script again. Essentially I think me generating the log is triggering the program to recognize the correct hour, leading it to enter the stopping process.

**Comment by AnykeyNL** [comment]
Are you sure you are running the script at the right time? Please enable permanent logging of each run of the script, so you can validate it always. You can do this by sending output to message service or use the > to output to a log file.

so: python AutoscaleAll.py > lastrun.log

**Comment by Bclavelmythics** [comment]
> Are you sure you are running the script at the right time? Please enable permanent logging of each run of the script, so you can validate it always. You can do this by sending output to message service or use the > to output to a log file.
> 
> so: python AutoscaleAll.py > lastrun.log

What do you mean running the script at the right time? Once you run the script once shouldn't it take care of the startup and shutdowns from that point forward, utilizing the tags attached to the instances that govern its uptime?

**Comment by AnykeyNL** [comment]
No, the script does not loop or permanently run. You need to schedule it so that the script runs each hour.

**Comment by Bclavelmythics** [comment]
> No, the script does not loop or permanently run. You need to schedule it so that the script runs each hour.

The schedule ended up being part of the issue. The default crontab had the startup script running every hour at 01 (ie. 8:01, 9:01) however the shutdown script ran every hour at 58. This was causing the shutdown script to not run until 8:58 and only then did the script recognize the 0 for 8pm and then shutdown. All I had to do was change the crontab to 01 so that the shutdown script would run at 8:01 and recognize that the instance is not supposed to be up during 8pm and it stops.
