### ISSUE TITLE
Not able to change the shape of Flexible Load Balancer

### ISSUE THREAD

**Issue by adeangelis01** [AnykeyNL/OCI-AutoScale#37]
Hello,

I am trying to lower a load balancer from 1000 mbps and when I specify a lower value in the load balancers tag, it does not update the load balancer.

When I run the command, I get the following output:
 python3 /home/opc/OCI-AutoScale/AutoScaleALL.py -a Down -ip

Checking test-lb (LoadBalancer) CurentState: ACTIVE...
 - Active schedule for test-lb:  1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,[100],100,100,1000,1000,1000,1000,1000,1000,1000,

When I run the command the following command I get:
 python3 AutoScaleALL.py -ip

Checking test-lb (LoadBalancer) CurentState: ACTIVE...
 - Active schedule for test-lb: 1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,[100],100,100,1000,1000,1000,1000,1000,1000,1000,
 - Upsizing loadbalancer from flexible to 100Mbps
 - Error Upsizing: Cannot update to 100Mbps shape from flexible shape.

Thank you.

**Comment by AnykeyNL** [comment]
The current script only supports the older dynamic shape, not the flex shape.

I can add support for the flex shape. Do you want to control the min, max or both values?

Please do keep in mind adjusting the loadbalancer can cause some lost connections:
_All existing connections to this load balancer will be reset during the update process and may take up to a minute, leading to potential connection loss._

**Comment by AnykeyNL** [comment]
Just updated the script to support the flex load balancer. The number specified in the schedule will be the new Max Bandwidth for the Flex Load Balancer. Let me know if this works for you.

**Comment by adeangelis01** [comment]
It works! Thank you so much!!
