### ISSUE TITLE
Issue after successful installation

### ISSUE THREAD

**Issue by muhammadaliraja** [AnykeyNL/OCI-AutoScale#39]
I am getting this error when testing and also after assigning name tag with instance its not working.

##########################################################################################
#                                   Running Auto Scale                                   #
##########################################################################################
Traceback (most recent call last):
  File "AutoScaleALL.py", line 1688, in <module>
    config, signer = OCIFunctions.create_signer(cmd.config_profile, cmd.is_instance_principals, cmd.is_delegation_token)
  File "/home/opc/OCI-AutoScale/OCIFunctions.py", line 61, in create_signer
    (config_profile if config_profile else oci.config.DEFAULT_PROFILE)
  File "/usr/lib/python3.6/site-packages/oci/config.py", line 107, in from_file
    raise ConfigFileNotFound("Could not find config file at {}, please follow the instructions in the link to setup the config file https://docs.cloud.oracle.com/en-us/iaas/Content/API/Concepts/sdkconfig.htm".format(expanded_file_location))
oci.exceptions.ConfigFileNotFound: Could not find config file at /root/.oci/config, please follow the instructions in the link to setup the config file https://docs.cloud.oracle.com/en-us/iaas/Content/API/Concepts/sdkconfig.htm
[root@instance-20240227-1814 OCI-AutoScale]# ^C

**Comment by AnykeyNL** [comment]
did you configure the OCI CLI for authentication to OCi with API key?

**Comment by muhammadaliraja** [comment]
I did steps as per YouTube video and created Name TAG and dynamic group authentication. There is no mention of CLI in OCI.

**Comment by AnykeyNL** [comment]
Are you using a dynamic group?if so are you running the script with the parameter -ip

**Comment by muhammadaliraja** [comment]
Yes dynamic group.
I created the TAG with " python3 CreateNameSpaces.py -ip" command and it created the TAGS. after that I assign it to an instance to check. and manually ran python3 AutoScaleALL.py

**Comment by AnykeyNL** [comment]
you need to run the AutoScallAll.py also with the -ip parameter, if you want authentication done thru dynamic group

**Comment by muhammadaliraja** [comment]
Done.
