### ISSUE TITLE
Multiple script runs are necessary to start/stop all virtual machines.

### ISSUE THREAD

**Issue by Reuenthal767** [AnykeyNL/OCI-AutoScale#4]
Hello @AnykeyNL thank you for your hard work on this script!

I'm experiencing this problem: on my environment the OCI-AutoScale script runs every hour (5 * * * *) but unfortunately not all machines are started (or stopped) in one go, it usually takes 2 or 3 script runs to have every vm in the desired state.

Have you ever encountered this issue? Could it be related to API Request Rate limits ( https://community.oracle.com/docs/DOC-1015335 )?

Maybe the multithreaded approach is too fast and raises a too many requests error ?.

**Comment by AnykeyNL** [comment]
Any idea how many stop/stop operations occur at the same time in your environment? Possibly it is the rate limit.

**Comment by Reuenthal767** [comment]
Thank you for your reply.
I'm starting around 60 VMs in the morning and stopping the same amount in the evening.
It will be a lot more in the future though.

**Comment by AnykeyNL** [comment]
I will create 100 vms in my environment and do some testing :-) Home my budget allows me to :-)

**Comment by Reuenthal767** [comment]
That would be awesome! Thanks!

**Comment by AnykeyNL** [comment]
Added rate limit support and tested it with 100VMs, my credit card is now over limit ;-) (kidding). All seems to work now.

**Comment by Reuenthal767** [comment]
That's amazing @AnykeyNL !
Thank you very much!
We all know that black AE does not have any limit :P
