### ISSUE TITLE
Can't find "Dynamic Group" menu in OCI

### ISSUE THREAD

**Issue by alexsorel** [AnykeyNL/OCI-AutoScale#41]
Hello, I'm being stuck already at the first step of your video, under "Identity" I can't find the "Dynamic Group" function. Not luckier when searching for it in the finder. Has it been renamed in OCI? Thanks for your help. Note: my instance is ARM Ubuntu, not AMD Oracle, does it make a difference?

**Comment by AnykeyNL** [comment]
Go to "identity & security" -> "Domains" -> Select your Identity Domain in the root folder -> On the left side you will find then the Dynamic Group Setup
