### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by webgeest** [AnykeyNL/OCI-AutoScale#6]
On the documentation of the wildcard, it seems that the asterisks are not displayed.

"When a wild card is used, the service will stay unmodified for that hour. For example, the below schedule will turn of a compute instance in the evening/night, but allows the user to manage the state during the day.

Schedule.AnyDay : 0,0,0,0,0,0,0,0,,,,,,,,,0,0,0,0,0,0,0,0 "

This should be 0,0,0,0,0,0,0,0,\*,\*,\*,\*,\*,\*,\*,\*,0,0,0,0,0,0,0,0  imho.

Use a backslash to escape the * Richard  :-)

**Comment by AnykeyNL** [comment]
Thanks! I fixed it in the markup text.

Op ma 16 nov. 2020 om 08:47 schreef webgeest <notifications@github.com>:

**Comment by webgeest** [comment]
Issue fixed in documentation.
