### ISSUE TITLE
Crontab might confuse schedule

### ISSUE THREAD

**Issue by webgeest** [AnykeyNL/OCI-AutoScale#7]
Note that the default crontab schedule performs down actions just before the hour, and up actions just after the hour.
So if a schedule is made as follows:
1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
the machine will be stopped at 5:58 and started at 6:01.
Maybe, it's more intuitive to schedule at minute 01 and 03, so that the hour (5 in this case) matches the 5th digit in the schedule.
This way, the machine will be stopped at 5:01 and started again at 6:03.
So that would match the idea of 1 hour downtime.

**Comment by AnykeyNL** [comment]
Today it does not really matter any more. I need to adjust this. In the time when we charged per hour, you wanted to schedule just before and just after. Today most services are per second. So just scheduling all operatings in one go, once per hour would be the recommended way to go I think.
